# Generated by Django 3.2.7 on 2021-09-25 16:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to='posts/post', verbose_name='Image')),
                ('alt_image', models.CharField(blank=True, help_text='The text that represents the image.', max_length=255, null=True, verbose_name='Alt image')),
                ('highlight', models.BooleanField(help_text='This post is a highlight? Note: Will show the three last created posts.', verbose_name='Highlight')),
                ('summary', models.CharField(help_text='This field is to show in the lists, a summary of post.', max_length=510, verbose_name='Summary')),
                ('body', ckeditor.fields.RichTextField(help_text='Body of post, save in html format.', verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
