# Generated by Django 3.2.7 on 2021-09-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='highlight',
            field=models.BooleanField(default=False, help_text='This post is a highlight? Note: Will show the three last created posts.', verbose_name='Highlight'),
        ),
    ]
