from django.utils.translation import ugettext_lazy as _

STATE_CHOICES = [
    ("AC", _("Acre")),
    ("AL", _("Alagoas")),
    ("AM", _("Amazonas")),
    ("AP", _("Amapá")),
    ("BA", _("Bahia")),
    ("CE", _("Ceará")),
    ("DF", _("Distrito Federal")),
    ("ES", _("Espírito Santo")),
    ("GO", _("Goiás")),
    ("MA", _("Maranão")),
    ("MG", _("Minas Gerais")),
    ("MS", _("Mato Grosso do Sul")),
    ("MT", _("Mato Grosso")),
    ("PA", _("Pará")),
    ("PB", _("Paraíba")),
    ("PE", _("Pernanbuco")),
    ("PI", _("Piauí")),
    ("PR", _("Paraná")),
    ("RJ", _("Rio de Janeiro")),
    ("RN", _("Rio Grande do Norte")),
    ("RO", _("Rondônia")),
    ("RR", _("Roraima")),
    ("RS", _("Rio Grande do Sul")),
    ("SC", _("Santa Catarina")),
    ("SE", _("Sergipe")),
    ("SP", _("São Paulo")),
    ("TO", _("Tocantins"))
]
