# Generated by Django 3.2.7 on 2021-10-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='catalogs/catalog', verbose_name='Image')),
                ('alt_image', models.CharField(blank=True, help_text='The text that represents the image.', max_length=255, null=True, verbose_name='Alt image')),
                ('products', models.ManyToManyField(related_name='catalogs', to='products.Product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Catolog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
    ]
