# Generated by Django 3.2.7 on 2021-10-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('title', models.CharField(help_text='Company name or slogan.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Description telling more about the company.', max_length=255, verbose_name='Description')),
                ('image', models.ImageField(upload_to='about_us/company', verbose_name='Image')),
                ('alt_image', models.CharField(blank=True, help_text='The text that represents the image.', max_length=255, null=True, verbose_name='Alt image')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone number')),
                ('cnpj', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='CNPJ')),
                ('motivation', models.TextField(blank=True, help_text='Why did you start the company? And why do you keep working on it every day?', max_length=255, null=True, verbose_name='Motivation')),
                ('principles', models.TextField(blank=True, help_text='Tell more about the principles of the company.', max_length=255, null=True, verbose_name='Principles')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('body', models.TextField(help_text='Body of email.', verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
