# Generated by Django 3.2.7 on 2021-10-11 01:55

import django.core.validators
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(db_index=True, help_text='Format example: 99.999.999/9999-99', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(help_text='Format example: (99) 99999-9999', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Invalid phone number', regex='\\(\\d{2,}\\) \\d{4,}\\-\\d{4}')], verbose_name='Phone number'),
        ),
    ]
