# Generated by Django 3.2.7 on 2021-10-17 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_auto_20211010_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='origin_zip_code',
            field=models.CharField(default=99000, help_text='Format example: 99999-999', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_origin_zip_code', message='Invalid origin zip code', regex='^\\d{5}\\-\\d{3}$')], verbose_name='Origin zip code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(help_text='Format example: (999) 99999-9999, (99) 9999-9999', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Invalid phone number', regex='^\\(\\d{2,3}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Phone number'),
        ),
    ]
