# Generated by Django 3.2.7 on 2021-10-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211010_1543'),
        ('accounts', '0002_auto_20211010_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccessed',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='user_accessed', through='accounts.ProductUserAccessed', to='products.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='user_favorite', to='products.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='usershopped',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='user_shopped', to='products.Product', verbose_name='Products'),
        ),
    ]
