# Generated by Django 3.2.7 on 2021-10-23 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211011_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='origin_destination_zip_codezip_code',
            field=models.CharField(default='', help_text='Format example: 99999-999', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_origin_zip_code', message='Invalid origin zip code', regex='^\\d{5}\\-\\d{3}$')], verbose_name='Origin zip code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcart',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of freight.', max_digits=9, verbose_name='Freight'),
        ),
    ]
