# Generated by Django 3.2.7 on 2021-10-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_origin_destination_zip_codezip_code_cart_destination_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='freight',
            field=models.DecimalField(decimal_places=2, help_text='Cost of freight.', max_digits=9, verbose_name='Freight'),
        ),
    ]
