# Generated by Django 3.2.7 on 2021-10-23 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_productcart_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of freight.', max_digits=9, null=True, verbose_name='Freight'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='(16) 99153-6813', help_text='Format example: (999) 99999-9999, (99) 9999-9999', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Invalid phone number', regex='^\\(\\d{2,3}\\) \\d{4,5}\\-\\d{4}$')], verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
