# Generated by Django 3.2.7 on 2021-11-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211124_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddresses',
            options={'verbose_name': 'User Addresses', 'verbose_name_plural': 'Users Addresses'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='destination_zip_code',
        ),
    ]
