# Generated by Django 3.2.7 on 2021-10-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('link', models.URLField(db_index=True, help_text='Link to page of some product.', max_length=255, verbose_name='Link')),
                ('image', models.ImageField(upload_to='managements/banner', verbose_name='Image')),
                ('alt_image', models.CharField(blank=True, help_text='The text that represents the image.', max_length=255, null=True, verbose_name='Alt image')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('link', models.URLField(db_index=True, help_text='Link to Promotion.', max_length=255, verbose_name='Link')),
                ('image', models.ImageField(upload_to='managements/promotion', verbose_name='Image')),
                ('alt_image', models.CharField(blank=True, help_text='The text that represents the image.', max_length=255, null=True, verbose_name='Alt image')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('most_acessed', models.BooleanField(default=True, help_text='Most acessed is active?', verbose_name='Most acessed')),
                ('most_sold', models.BooleanField(default=True, help_text='Most sold is active?', verbose_name='Most sold')),
                ('most_favorite', models.BooleanField(default=True, help_text='Most favorite is active?', verbose_name='Most favorite')),
                ('banners', models.ManyToManyField(help_text='Banners that will show in home.', related_name='home', to='managements.Banner', verbose_name='Banners')),
                ('categories', models.ManyToManyField(help_text='Categories that will show in home.', related_name='home', to='products.Category', verbose_name='Categories')),
                ('posts', models.ManyToManyField(help_text='Posts that will show in home.', related_name='home', to='posts.Post', verbose_name='Posts')),
                ('promotions', models.ManyToManyField(help_text='Promotions that will show in home.', related_name='home', to='managements.Promotion', verbose_name='Promotions')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Main Page',
            },
        ),
    ]
