# Generated by Django 3.2.7 on 2021-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active'),
        ),
    ]
