# Generated by Django 3.2.7 on 2021-10-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211010_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='This register is active? If set as no, will show in website!', verbose_name='Active')),
                ('format', models.PositiveSmallIntegerField(choices=[(1, 'Packege or Box'), (2, 'Prism Roll'), (3, 'Envelope')], default=1, verbose_name='format')),
                ('weight', models.DecimalField(decimal_places=3, default=0, help_text='Unit of measurement: kilogram(kg). If the format is Envelope the limit of weight is 1kg.', max_digits=9, verbose_name='weight')),
                ('height', models.PositiveIntegerField(default=0, help_text='Unit of measurement: centimeter(cm).', verbose_name='height')),
                ('width', models.PositiveIntegerField(default=0, help_text='Unit of measurement: centimeter(cm).', verbose_name='width')),
                ('length', models.PositiveIntegerField(default=0, help_text='Unit of measurement: kilogram(cm).', verbose_name='length')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
