# Generated by Django 3.2.7 on 2021-10-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.PositiveIntegerField(default=0, help_text='Unit of measurement: centimeter(cm).', verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Unit of measurement: kilogram(kg). In case the format is Envelope the limit of weight is 1kg.', max_digits=9, verbose_name='weight'),
        ),
    ]
