# Generated by Django 3.2.7 on 2021-10-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211023_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Packege or Box'), (3, 'Envelope')], default=1, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='Unit of measurement: centimeter(cm). In case the format is Package or Box the range of weight is 1cm <=> 100cm.Fill only if the format is Package or Box!', verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.PositiveIntegerField(default=0, help_text='Unit of measurement: centimeter(cm). In case the format is Package or Box the range of length is 15cm <=> 100cm.In case the format is Envelope the range of length is 16cm <=> 60cm. ', verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Unit of measurement: kilogram(kg). In case the format is Package or Box the limit of weight is 30kg (SEDEX 10 10kg).In case the format is Envelope the limit of weight is 1kg. ', max_digits=9, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.PositiveIntegerField(default=0, help_text='Unit of measurement: centimeter(cm). In case the format is Package or Box the range of weight is 10cm <=> 100cm.In case the format is Envelope the range of width is 11cm <=> 60cm. ', verbose_name='width'),
        ),
    ]
