# Generated by Django 3.2.7 on 2021-10-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211023_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='freight',
        ),
    ]
